# Welcome to Jekyll!

# Website settings
title: Mengyuan Zhu
description: Mengyuan's blog,use Jekyll and github pages.
keywords: Jekyll, github, Mengyuan
baseurl:   # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: http://MengyuanZhu.github.io/  # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: static/assets/img/  # url should be '/homepage/static/assets/img/blog' as before

# author -- index page "about me" section
author:  # change following line to your infomation.
  name: MengyuanZhu  # Be used at blog posts' author.
  first_name: Mengyuan  # Be used at index page about me section.
  last_name: Zhu  # Be used at index page about me section.
  avatar: static/assets/img/landing/avatar.jpg  # upload your avatar at directory and edit it.
  github_username: MengyuanZhu  # Leave blank if you don't have now
  linkedin_id: mengyuan-zhu # Leave blank if you don't have now
  email: zhumengyuan1024@gmail.com  # Leave blank if you don't have now
  cv: # A online CV can be printed as PDF, leave blank if you don't have now

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
